{% set name = "xdggs" %}
{% set version = "0.3.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xdggs-{{ version }}.tar.gz
  sha256: 90d008b6b742e8646a967fe34dd50213dd6dd3f2d28e64c3a85995d4ac0e4a2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - xarray
    - cdshealpix
    - h3ronpy
    - typing_extensions
    - lonboard >=0.9.3
    - pyproj >=3.3
    - matplotlib-base
    - arro3-core >=0.4.0
    - healpix-geo >=0.0.6
    - pooch

test:
  imports:
    - xdggs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/xarray-contrib/xdggs
  summary: Xarray extension for DGGS
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keewis
    - benbovy
