{% set name = "xdggs" %}
{% set version = "0.6.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xdggs-{{ version }}.tar.gz
  sha256: 34a8ffdaa914de2f1001640c3e5cc3d92f4f59ebf69d786e68f9b229ff22b2f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - xarray
    - numpy >=2.0
    - cdshealpix
    - h3ronpy
    - typing_extensions
    - lonboard >=0.9.3
    - pyproj >=3.3
    - matplotlib-base
    - arro3-core >=0.4.0
    - healpix-geo >=0.0.6
    - pooch
    - anywidget
    - traitlets
    - ipywidgets

test:
  imports:
    - xdggs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/xarray-contrib/xdggs
  summary: Xarray extension for DGGS
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keewis
    - benbovy
